POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Teste"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/73bacd59-391e-45b7-9857-173e2d88d44a